### ISSUE TITLE
Roadmap to v1

### ISSUE THREAD

**Issue by AliveDevil** [iterate-ch/cloudfiles-troubleshooter#1]
Features to be implemented for v1:
- [X] Implement `--Confirm` for-real
- [X] Implement `--WhatIf` for-real
- [X] Implement "Clean"-command
  - [ ] Alternative way of querying the Shell-namespace,
  so that when `StorageProviderSyncRootManager` either
    - doesn't have that Sync Root registered/known anymore
    - or more aggressive means are necessary to clean a sync root registration.
    - there is ambiguity with registrations (they all use the same Display Name)
- [ ] Dump known information about a Sync Root
  - By Name
  - By Id
  - By Path

Optional nice-to-have:
- [ ] Intentionally create broken Sync Roots
- [ ] #2 
- [ ] #3
